name: {{project_name.snakeCase()}}
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.3
  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  duration: ^3.0.13
  flash: ^3.0.5+1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  path_provider: ^2.1.1
  platform_info: ^4.0.2
  responsive_framework: ^1.1.1
  talker_dio_logger: ^2.3.0
  talker_flutter: ^3.2.7
  velocity_x: ^4.1.1

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  riverpod_lint: ^2.0.0
  riverpod_test: ^0.1.3
  very_good_analysis: ^5.0.0

# Added temporary for custom lint and riverpod lint
dependency_overrides:
  analyzer: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
