name: {{project_name.snakeCase()}}
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


 # Added for support WASM
dependency_overrides:
  flutter_secure_storage_web: ^2.0.0-beta.1


flutter:
  uses-material-design: true
  generate: true