name: {{project_name.snakeCase()}}
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


dev_dependencies:

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  generate: true
